-- Tabela de Oficinas (Tenants) - Já deve existir pelo Auth do Next.js, mas garantindo ref
CREATE TABLE IF NOT EXISTS public.oficinas (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    nome TEXT,
    email TEXT,
    senha_hash TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina_id UUID REFERENCES public.oficinas(id) NOT NULL,
    nome TEXT NOT NULL,
    telefone TEXT NOT NULL,
    carro TEXT NOT NULL,
    placa TEXT,
    km_media_mensal INTEGER DEFAULT 1000,
    ativo BOOLEAN DEFAULT true,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Tipos de Serviço
CREATE TABLE IF NOT EXISTS public.tipos_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina_id UUID REFERENCES public.oficinas(id), -- Opcional se for global, mas ideal ser por oficina
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    intervalo_km INTEGER NOT NULL,
    descricao TEXT,
    ativo BOOLEAN DEFAULT true
);

-- Tabela de Serviços Realizados
CREATE TABLE IF NOT EXISTS public.servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina_id UUID REFERENCES public.oficinas(id) NOT NULL,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE CASCADE NOT NULL,
    tipo_servico_id BIGINT REFERENCES public.tipos_servico(id) NOT NULL,
    km_realizado INTEGER NOT NULL,
    valor DECIMAL(10,2),
    observacoes TEXT,
    data_servico DATE NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Notificações
CREATE TABLE IF NOT EXISTS public.notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina_id UUID REFERENCES public.oficinas(id) NOT NULL,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE CASCADE NOT NULL,
    servico_id BIGINT REFERENCES public.servicos(id),
    tipo_servico_id BIGINT REFERENCES public.tipos_servico(id) NOT NULL,
    mensagem TEXT NOT NULL,
    km_previsto INTEGER,
    enviada BOOLEAN DEFAULT false,
    data_envio TIMESTAMP WITH TIME ZONE,
    erro TEXT,
    tentativas INTEGER DEFAULT 0,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Configurações
CREATE TABLE IF NOT EXISTS public.configuracoes (
    chave TEXT PRIMARY KEY,
    valor TEXT NOT NULL,
    descricao TEXT,
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_clientes_telefone ON public.clientes(telefone);
CREATE INDEX IF NOT EXISTS idx_servicos_cliente_id ON public.servicos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_servicos_data_servico ON public.servicos(data_servico);
CREATE INDEX IF NOT EXISTS idx_notificacoes_cliente_id ON public.notificacoes(cliente_id);
CREATE INDEX IF NOT EXISTS idx_notificacoes_enviada ON public.notificacoes(enviada);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipos_servico ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.servicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracoes ENABLE ROW LEVEL SECURITY;

-- Políticas de Segurança (Exemplo simples: permitir tudo para autenticados e service role)
-- Ajuste conforme necessário para sua lógica de auth
CREATE POLICY "Acesso total para service role" ON public.clientes
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Acesso total para service role" ON public.tipos_servico
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Acesso total para service role" ON public.servicos
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Acesso total para service role" ON public.notificacoes
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Acesso total para service role" ON public.configuracoes
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Dados iniciais de Tipos de Serviço (Seed)
INSERT INTO public.tipos_servico (codigo, nome, intervalo_km, descricao) 
VALUES 
    ('troca_oleo', 'Troca de Óleo do Motor', 5000, 'Troca de óleo lubrificante do motor'),
    ('filtro_oleo', 'Filtro de Óleo', 10000, 'Substituição do filtro de óleo'),
    ('correia_dentada', 'Correia Dentada', 60000, 'Substituição da correia dentada'),
    ('filtro_ar', 'Filtro de Ar', 15000, 'Substituição do filtro de ar do motor'),
    ('filtro_combustivel', 'Filtro de Combustível', 20000, 'Substituição do filtro de combustível'),
    ('velas', 'Velas de Ignição', 30000, 'Substituição das velas de ignição'),
    ('pastilhas_freio', 'Pastilhas de Freio', 40000, 'Troca das pastilhas de freio'),
    ('fluido_freio', 'Fluido de Freio', 20000, 'Troca do fluido de freio'),
    ('alinhamento', 'Alinhamento e Balanceamento', 10000, 'Alinhamento e balanceamento das rodas'),
    ('revisao_geral', 'Revisão Geral', 10000, 'Revisão completa do veículo')
ON CONFLICT (codigo) DO NOTHING;
